# Generated by Django 5.1.14 on 2026-01-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PASSWORD_RESET', 'Password Reset'), ('ROLE_CHANGE', 'Role Change'), ('DOCUMENT_UPLOAD', 'Document Upload'), ('DOCUMENT_VIEW', 'Document View'), ('DOCUMENT_DOWNLOAD', 'Document Download'), ('DOCUMENT_UPDATE', 'Document Update'), ('DOCUMENT_DELETE', 'Document Delete'), ('DOCUMENT_ARCHIVE', 'Document Archive')], max_length=20),
        ),
    ]
