# Generated by Django 5.1.14 on 2026-01-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_update_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PASSWORD_RESET', 'Password Reset'), ('ROLE_CHANGE', 'Role Change'), ('ACCOUNT_ACTIVATE', 'Account Activate'), ('ACCOUNT_DEACTIVATE', 'Account Deactivate'), ('DOCUMENT_UPLOAD', 'Document Upload'), ('DOCUMENT_VIEW', 'Document View'), ('DOCUMENT_DOWNLOAD', 'Document Download'), ('DOCUMENT_UPDATE', 'Document Update'), ('DOCUMENT_DELETE', 'Document Delete'), ('DOCUMENT_ARCHIVE', 'Document Archive'), ('DOCUMENT_FOLDER_CREATE', 'Document Folder Create'), ('DOCUMENT_FOLDER_UPDATE', 'Document Folder Update')], max_length=30),
        ),
    ]
