# Generated by Django 5.1.14 on 2026-01-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_archived_at_document_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='section',
            field=models.CharField(choices=[('GENERAL', 'General'), ('POLICIES', 'Policies'), ('PROCEDURES', 'Procedures'), ('FORMS', 'Forms'), ('REPORTS', 'Reports'), ('TEMPLATES', 'Templates')], default='GENERAL', max_length=50),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['section'], name='documents_d_section_6b70d2_idx'),
        ),
    ]
