# Generated by Django 5.1.14 on 2026-02-12 00:00

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.document_upload_path),
        ),
        migrations.AddField(
            model_name='document',
            name='google_docs_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='google_sheets_url',
            field=models.URLField(blank=True),
        ),
    ]
